name = "binarygate"
compatibility_date = "2025-02-15"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[containers]]
name = "CONTAINER"
class_name = "BinarygateContainer"
image = "./Dockerfile"

[durable_objects]
bindings = [{ name = "CONTAINER_DO", class_name = "BinarygateContainer" }]
