name = "binarygate"
compatibility_date = "2025-02-15"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
minify = true

[env]
vars = { }

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BinarygateContainer"]

[[containers]]
name = "container"
class_name = "BinarygateContainer"
image = "./Dockerfile"

[durable_objects]
bindings = [{ name = "CONTAINER_DO", class_name = "BinarygateContainer" }]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
